### ISSUE TITLE
Target net6.0-windows

### ISSUE THREAD

**Issue by Arithmomaniac** [RickStrahl/SetResolution#1]
https://github.com/RickStrahl/SetResolution/blob/5c00a228ef9416e19866168bdf8eb0ff19eff8d1/SetResolution/Westwind.SetResolution.csproj#L55

Using `net6.0-windows` would prevent it from being available (uselessly) IIRC.

**Comment by RickStrahl** [comment]
Funny that occurred to me today as well. Will update tomorrow.

**Comment by RickStrahl** [comment]
Turns out packages don't allow for platform specific targets - so `net6.0-windows` is not allowed.

![image](https://user-images.githubusercontent.com/1374013/206627469-c1aaf400-92e1-4f18-979e-51a6576db756.png)


I'll add a note to the description to minimize use outside of Windows.

**Comment by Arithmomaniac** [comment]
🫤

In addition to the description, you could also check `RuntimeInformation.IsOSPlatform(OSPlatform.Windows)` on tool launch and fail fast on MacOS/Linux

**Comment by RickStrahl** [comment]
LOL - if somebody installs this tool with Windows in the title description and runs in on Linux, I think I'm not too worried about a nasty system error message :smile:
